sudo: false
language: ruby

before_install:
- gem install bundler -v 1.13.7

install:
- bundle install --with "$GEMSETS"

script:
- bundle exec rake

jobs:
  include:
  - stage: test
    env: GEMSETS=test
    rvm: jruby-19mode
  - stage: test
    env: GEMSETS=test
    rvm: 1.9.3
  - stage: test
    env: GEMSETS=test
    rvm: 2.0.0
  - stage: test
    env: GEMSETS=test
    rvm: 2.1.8
  - stage: test
    env: GEMSETS="test sidekiq"
    rvm: 2.2.4
  - stage: test
    env: GEMSETS="test sidekiq coverage"
    rvm: 2.3.0
