language: ruby
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
- jruby-18mode
- jruby-19mode
- 1.8.7
before_install:
- gem update --system 2.1.11
- gem --version
notifications:
  hipchat:
    rooms:
      secure: cv5V8ivZExOywKL9n0CODnxy9m5u4rQ5ZMYK8XHPIoqQKkvH9DQOeb2ItW2aM2kxeupJEcQEy1Eu4sYMGhyzKUNdqbFtQBhDYxRwSAgTRIkGlHQCnznyExHWZbGfDB8y/m11HiZ1wuPuqs8ZZ+VccNb4bwJKbhPTbf1RZ+GPeU8=
